<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[4]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[5]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[6]=array(0,1,1,'5bm754Gv54mH');
$cfg_Cs[7]=array(2,1,1,'5qSF5a2Q57O75YiX');
$cfg_Cs[8]=array(2,1,1,'6aSQ5qGM57O75YiX');
$cfg_Cs[9]=array(2,1,1,'5rKZ5Y+R57O75YiX');
$cfg_Cs[10]=array(2,1,1,'5Yib5oSP57O75YiX');
$cfg_Cs[11]=array(1,1,1,'5LyB5Lia566A5LuL');
$cfg_Cs[12]=array(1,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[13]=array(1,1,1,'6K6+6K6h5Zui6Zif');
$cfg_Cs[14]=array(0,1,1,'5Zyw5Zu+');
?>