<?php
$z[0]=Array("global","",124,156);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",421,443);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",640,664);
$z[2][4]['name']="cfg_email";
$z[3]=Array("global","",863,887);
$z[3][4]['name']="cfg_place";
$z[4]=Array("global","",1214,1240);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1241,1267);
$z[5][4]['name']="cfg_webname";

?>