<?php
$z[0]=Array("global","",139,171);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",293,319);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n			<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n			",1452,1752);
$z[2][4]['row']="5";
$z[2][4]['type']="top";
$z[2][4]['col']="1";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~> <span>~typename~</span> </a> </li>";
$z[3]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a></li>\r\n		",1957,2079);
$z[3][4]['typeid']="6";

?>